### ISSUE TITLE
File source require file to be exists

### ISSUE THREAD

**Issue by e11it** [micro/go-config#48]
HI!

I have setup two source for config(env and file) and got error: "file doesn't exists".

I expected that second source is optional.

May be it's better to be able to make file optional and don't return error if defined more than one source for config?

**Comment by e11it** [comment]
One more. I have made invalid yaml config file but didn't receive any exception.
In this place I expected to get error.

Example config file with error:

```yaml
--
Kafka:
  Brokers:
  - "127.0.0.1:9092"
  Topics:
  - "ohs"
  GroupID: "go-kafka"
```
