### ISSUE TITLE
Use env vars inside a configuration yaml

### ISSUE THREAD

**Issue by javib51** [micro/go-config#91]
Hello there!

I am new using this library and I am missing a feature that it is commun in config libraries in other languages. 

Now, the way to declare a config yaml is similar to:
```
databases:
  mysql:
    host: 'localhost'
    port: 3306
    user: someuser
    password: somepwd
    schema: someschema
```

I would like to be able to use env vars as value of my params. Something like this:
```
databases:
  mysql:
    host: 'localhost'
    port: 3306
    user:  ${MYSQL_DB_USER}
    password: ${MYSQL_DB_PWD}
    schema: someschema
```

What do you think?
